services:
  - type: web
    name: mockmind-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: firebase-service-account.json
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: RENDER_EXTERNAL_URL
        value: https://mockmind-backend-x1qz.onrender.com
      - key: FIREBASE_PROJECT_ID
        value: mockmindai
